# This is a theme generated by ~/.config/nvim/lua/color-tool.lua

function fish_handle_background_color_change \
    --description 'Handle changing the background color' \
    --on-variable fish_background_color

    switch $fish_background_color
        case light
            set --global fish_color_normal 030303 # fg: #030303
            set --global fish_color_command 018a79 # fg: #018a79
            set --global fish_color_keyword eb9601 --bold # fg: #eb9601
            set --global fish_color_quote 005524 --background ccedd1 # fg: #005524 bg: #ccedd1
            set --global fish_color_redirection eb9601 # fg: #eb9601
            set --global fish_color_end e34041 # fg: #e34041
            set --global fish_color_error df0024 # fg: #df0024
            set --global fish_color_param eb9601 --italics # fg: #eb9601
            set --global fish_color_comment 919191 # fg: #919191
            set --global fish_color_selection --background bdeeed # bg: #bdeeed
            set --global fish_color_operator eb9601 # fg: #eb9601
            set --global fish_color_escape e34041 --background ccedd1 # fg: #e34041 bg: #ccedd1
            set --global fish_color_autosuggestion 919191 # fg: #919191
            set --global fish_color_cancel 2e2e2e --background e8e8e8 --italics # fg: #2e2e2e bg: #e8e8e8
            set --global fish_color_search_match --background fce094 # bg: #fce094
            set --global fish_color_history_current --bold #
            set --global fish_pager_color_progress 018f41 # fg: #018f41
            set --global fish_pager_color_background --background ffffff # bg: #ffffff
            set --global fish_pager_color_prefix e34041 # fg: #e34041
            set --global fish_pager_color_completion 030303 # fg: #030303
            set --global fish_pager_color_description 919191 # fg: #919191
            set --global fish_pager_color_selected_background --background bdeeed # bg: #bdeeed
            set --global fish_prompt_color_mode_normal_fg f6f6f6 # #f6f6f6
            set --global fish_prompt_color_mode_normal_bg 01c4c4 # #01c4c4
            set --global fish_prompt_color_mode_normal_decorations --bold
            set --global fish_prompt_color_mode_insert_fg f6f6f6 # #f6f6f6
            set --global fish_prompt_color_mode_insert_bg 007fbc # #007fbc
            set --global fish_prompt_color_mode_insert_decorations --bold
            set --global fish_prompt_color_mode_replace_fg f6f6f6 # #f6f6f6
            set --global fish_prompt_color_mode_replace_bg ae6001 # #ae6001
            set --global fish_prompt_color_mode_replace_decorations --bold
            set --global fish_prompt_color_mode_visual_fg f6f6f6 # #f6f6f6
            set --global fish_prompt_color_mode_visual_bg 008889 # #008889
            set --global fish_prompt_color_mode_visual_decorations --bold
            set --global fish_cursor_color_normal "\e]12;rgb:01/c4/c4\e\\" # bg: #01c4c4
            set --global fish_cursor_color_insert "\e]12;rgb:00/7f/bc\e\\" # bg: #007fbc
            set --global fish_cursor_color_replace "\e]12;rgb:ae/60/01\e\\" # bg: #ae6001

        case '*'
            set --global fish_color_normal ffffff # fg: #ffffff
            set --global fish_color_command 56c1af # fg: #56c1af
            set --global fish_color_keyword ffa92f --bold # fg: #ffa92f
            set --global fish_color_quote aef8bd --background 314d36 # fg: #aef8bd bg: #314d36
            set --global fish_color_redirection ffa92f # fg: #ffa92f
            set --global fish_color_end ff5e5a # fg: #ff5e5a
            set --global fish_color_error ff3f43 # fg: #ff3f43
            set --global fish_color_param ffa92f --italics # fg: #ffa92f
            set --global fish_color_comment 919191 # fg: #919191
            set --global fish_color_selection --background 386565 # bg: #386565
            set --global fish_color_operator ffa92f # fg: #ffa92f
            set --global fish_color_escape ff5e5a --background 314d36 # fg: #ff5e5a bg: #314d36
            set --global fish_color_autosuggestion 919191 # fg: #919191
            set --global fish_color_cancel ffffff --background 414141 --italics # fg: #ffffff bg: #414141
            set --global fish_color_search_match --background ab9045 # bg: #ab9045
            set --global fish_color_history_current --bold #
            set --global fish_pager_color_progress 55c675 # fg: #55c675
            set --global fish_pager_color_background --background 2e2e2e # bg: #2e2e2e
            set --global fish_pager_color_prefix ff5e5a # fg: #ff5e5a
            set --global fish_pager_color_completion ffffff # fg: #ffffff
            set --global fish_pager_color_description 919191 # fg: #919191
            set --global fish_pager_color_selected_background --background 386565 # bg: #386565
            set --global fish_prompt_color_mode_normal_fg 363636 # #363636
            set --global fish_prompt_color_mode_normal_bg 67fdfd # #67fdfd
            set --global fish_prompt_color_mode_normal_decorations --bold
            set --global fish_prompt_color_mode_insert_fg 363636 # #363636
            set --global fish_prompt_color_mode_insert_bg 52b5f6 # #52b5f6
            set --global fish_prompt_color_mode_insert_decorations --bold
            set --global fish_prompt_color_mode_replace_fg 363636 # #363636
            set --global fish_prompt_color_mode_replace_bg e9964d # #e9964d
            set --global fish_prompt_color_mode_replace_decorations --bold
            set --global fish_prompt_color_mode_visual_fg 363636 # #363636
            set --global fish_prompt_color_mode_visual_bg 56bfc0 # #56bfc0
            set --global fish_prompt_color_mode_visual_decorations --bold
            set --global fish_cursor_color_normal "\e]12;rgb:01/c4/c4\e\\" # bg: #01c4c4
            set --global fish_cursor_color_insert "\e]12;rgb:52/b5/f6\e\\" # bg: #52b5f6
            set --global fish_cursor_color_replace "\e]12;rgb:e9/96/4d\e\\" # bg: #e9964d
    end
end

function fish_vi_cursor_handle_color \
    --description 'Set the cursor color for the current mode.' \
    --on-variable fish_bind_mode \
    --on-event fish_postexec \
    --on-event fish_focus_in

    if not contains $fish_key_bindings \
            fish_vi_key_bindings fish_hybrid_key_bindings

        return
    end

    switch $fish_bind_mode
        case insert
            echo -en $fish_cursor_color_insert
        case replace replace_one
            echo -en $fish_cursor_color_replace
        case '*'
            echo -en $fish_cursor_color_normal
    end
end

function fish_vi_cursor_handle_preexec_color \
    --description 'Set the cursor color for the neutral cursor.' \
    --on-event fish_preexec

    echo -en $fish_cursor_color_normal
end

fish_handle_background_color_change

set fish_cursor_default block blink
set fish_cursor_insert line blink
set fish_cursor_replace underscore blink
set fish_cursor_replace_one underscore blink
set fish_cursor_visual block